// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czdvdbxtmxmrhwfyicpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6ZHZkYnh0bXhtcmh3ZnlpY3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTk4MzUsImV4cCI6MjA2NDIzNTgzNX0.CLYbHXO52CAospfOX1g668eIcEFa0yFYKgFW8xlr1gg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);